# Generated by Django 4.1.1 on 2023-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('expire', models.DateTimeField()),
                ('login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
